### ISSUE TITLE
build the webp-imageio.dll

### ISSUE THREAD

**Issue by sicmu** [nintha/webp-imageio-core#1]
I clone the webp-imageio by Sourcetree, but the folder "libwebp" clone fail.
When I run cmake .. and it keep throwing error:
CMake Error at CMakeLists.txt:6 (add_subdirectory): add_subdirectory given source "libwebp" which is not an existing directory.

how do you build the webp-imageio.dll?

**Comment by nintha** [comment]
The lib is base on https://bitbucket.org/luciad/webp-imageio, so I only build low version lib.

**Comment by nintha** [comment]
@sicmu the way to compile webp-imageio.dll https://github.com/nintha/webp-imageio-core#compiling-the-native-library
