### ISSUE TITLE
Decode returned code VP8_STATUS_UNSUPPORTED_FEATURE

### ISSUE THREAD

**Issue by chunzhenzyd** [nintha/webp-imageio-core#11]
File file = new File("ezgif.com-gif-maker.webp");
Thumbnails.of(file).scale(0.5).toFile(file.getAbsolutePath() + ".thumbnail.jpg");

**Comment by nintha** [comment]
Could you provide more detail of the code? I don't know what is `Thumbnails`.

**Comment by chunzhenzyd** [comment]
> Could you provide more detail of the code? I don't know what is `Thumbnails`.

Hi nintha,
Thumbnails libraray:
net.coobird:thumbnailator:0.4.8
I want to scale a webp picture ezgif.com-gif-maker.webp to half.

**Comment by nintha** [comment]
This project just wrap java code and dll files. You may go to source repo [luciad/webp-imageio](https://bitbucket.org/luciad/webp-imageio) , and create issue about supporting new feature of animation webp.
