### ISSUE TITLE
UnsatisfiedLinkError: Can't find dependent libraries on windows 10

### ISSUE THREAD

**Issue by zakgof** [nintha/webp-imageio-core#2]
When I try to run it on Windows 10, I get

`java.lang.UnsatisfiedLinkError: C:\Users\username\AppData\Local\Temp\webp-imageio4809108976093338957.dll: Can't find dependent libraries`

Apparently, the dll has some missing dependencies

**Comment by boonyachengdu** [comment]
> When I try to run it on Windows 10, I get
> 
> `java.lang.UnsatisfiedLinkError: C:\Users\username\AppData\Local\Temp\webp-imageio4809108976093338957.dll: Can't find dependent libraries`
> 
> Apparently, the dll has some missing dependencies

java.lang.UnsatisfiedLinkError: C:\Windows\Temp\webp-imageio5949079060736136885.dll: Can't find dependent libraries  Hello did you deal with it?

**Comment by zakgof** [comment]
Well, I ended up implementing my own libwebp wrapper https://github.com/zakgof/webp4j

**Comment by boonyachengdu** [comment]
> Well, I ended up implementing my own libwebp wrapper https://github.com/zakgof/webp4j

Thanks for your answer!  Did the original code dll for x64 is bad for my windows x64 OS? Have you rebuid your dll on your windows system?

**Comment by zakgof** [comment]
I rebuilt the dll. No idea what's wrong with this project's oneOn Mar 25, 2019 11:05 AM, Manlan Peng <notifications@github.com> wrote:
Well, I ended up implementing my own libwebp wrapper https://github.com/zakgof/webp4j

Thanks for your answer!  Did the original code dll for x64 is bad for my windows x64 OS? Have you rebuid your dll on your windows system?

**Comment by nintha** [comment]
Is in version 1.0.0 or 1.0.1?

**Comment by nikkiw** [comment]
I have the same problem in version 1.0.1, there is no such problem in version 1.0.0. Windows 10 64-bit Operating System

**Comment by rakeshkonda** [comment]
@zakgof  Could you please tell me how to rebuild the jar file. i have the same issue unsatisfied link error

**Comment by nintha** [comment]
@boonyachengdu @rakeshkonda the way to compile native library https://github.com/nintha/webp-imageio-core#compiling-the-native-library

**Comment by egloffmark** [comment]
I had the same issue on a Windows 10 System. I solved this by analyzing and installing the missing dll dependencies of the temporary "webp-imageio.dll". In my case the following dependencies have been missing. So I put these into "C:\Windows\System32" directory:
- vcruntime140d.dll
- ucrtbased.dll

Tool to analyze the DLL dependencies on Windows:
- https://lucasg.github.io/Dependencies/  => start then the "DependenciesGui.exe" and drag and drop the dll file which you like to  analyze

to get  vcruntime140 you need to download Microsoft Visual C++ Redistributable Version
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 or https://aka.ms/vs/17/release/vc_redist.x64.exe  this should then automatically install the library on your windows system and no copy to system32 folder should be necessary 
*Remark:* I had to rename the "vcruntime140.dll" simple to "vcruntime140d.dll" don't ask me why. The "d" version is the debug version. However I assume the trick by renaming it may do it. 

For the "ucrtbased.dll" you need to get the VS2022 Community installed. https://visualstudio.microsoft.com/downloads/ or Windows SDK download https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/ it get then for instance installed into C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\ucrt\ucrtbased.dll this then you can copy to your "System32" directory 

After that your dependencies on windows should work.

![image](https://github.com/nintha/webp-imageio-core/assets/7382336/6ecd3d0c-0df3-47b4-80df-965c66ca9291)
