### ISSUE TITLE
does this mean animated webp can not convert to gif?

### ISSUE THREAD

**Issue by Andreby42** [nintha/webp-imageio-core#3]
I just try to convert an animated webp file to a animated gif file,when run the demo code something happened,this is the demo:
 
       `public static void main(String[] args) throws IOException {

		String inputPath = "/demo01.webp";String outputGifPath = "test_pic/test_.gif";

		// Obtain a WebP ImageReader instance
		ImageReader reader = ImageIO.getImageReadersByMIMEType("image/webp").next();
		// Configure decoding parameters
		WebPReadParam readParam = new WebPReadParam();
		readParam.setBypassFiltering(true);

		// Configure the input on the ImageReader
		try {
			reader.setInput(new FileImageInputStream(new File(inputPath)));
		} catch (IOException e) {
			e.printStackTrace();
		}

		// Decode the image
		BufferedImage image = reader.read(0, readParam);
		ImageIO.write(image, "gif", new File(outputGifPath));
	}`
and this is the exception
`Exception in thread "main" java.io.IOException: Decode returned code VP8_STATUS_UNSUPPORTED_FEATURE
	at com.luciad.imageio.webp.WebP.decode(WebP.java:61)
	at com.luciad.imageio.webp.WebPReader.read(WebPReader.java:158)
	at com.andy.main(Test.java:281)`

should I  compile the  libwebp1.0.0  or the newer? 
`
0.1.0 版本用的库是 libwebp0.4.2，比较老了，
你可以自己编译 mac 环境的 libwebp1.0.0 的动态链接库。我手上没有 mac 机器，无能为力。` 
[https://segmentfault.com/a/1190000016324137](url)

**Comment by nintha** [comment]
yep, you can compile the libwebp1.0.0 or the newer.
