### ISSUE TITLE
system scope is deprecated in maven

### ISSUE THREAD

**Issue by MarcAgate** [nintha/webp-imageio-core#5]
There is another way to setup the whole thing when using maven and to avoid using the deprecated "system" scope.
You can install the jar locally on the target system as follows:

`mvn install:install-file -Dfile=webp-imageio-core-0.1.0.jar -DgroupId=my.group.id.webp> -DartifactId=webp-imageio -Dversion=0.1.0 -Dpackaging=jar`

and then just add to your pom.xml:

```
<dependency>      
        <groupId>your.group.id.webp</groupId>  
        <artifactId>webp-imageio</artifactId>  
        <version>0.1.0</version> 
    </dependency>
```
it's clean, simple and it works like a charm !

**Comment by kundana-boddeti** [comment]
what is we have multiple jar files to be used as dependency.Should we use mvn install:install-file for each and every file or is there a generic way of doing like a plugin to install multiple files..Help appreciated.
