### ISSUE TITLE
Docker Alpine Linux Container Crashing on Decode

### ISSUE THREAD

**Issue by erickgonzalez** [nintha/webp-imageio-core#6]
This is using an Alpine Linux image v3.9. 

When calling the decode method in the WebP.java is crashing the server when is trying to get the pixels

int[] pixels = decode(aOptions.fPointer, aData, aOffset, aLength, aOut, ByteOrder.nativeOrder().equals(ByteOrder.BIG_ENDIAN));

There is no error thrown on the logs, and here is the stacktrace:

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.luciad.imageio.webp.WebP.decode(J[BII[IZ)[I+0
j  com.luciad.imageio.webp.WebP.decode(Lcom/luciad/imageio/webp/WebPDecoderOptions;[BII[I)[I+64
j  com.luciad.imageio.webp.WebPReader.read(ILjavax/imageio/ImageReadParam;)Ljava/awt/image/BufferedImage;+53
j  javax.imageio.ImageIO.read(Ljavax/imageio/stream/ImageInputStream;)Ljava/awt/image/BufferedImage;+55
j  javax.imageio.ImageIO.read(Ljava/io/File;)Ljava/awt/image/BufferedImage;+51
j  com.dotmarketing.image.filter.ThumbnailImageFilter.runFilter(Ljava/io/File;Ljava/util/Map;)Ljava/io/File;+312
```

On others OS (Win, Ubuntu and MacOs) works without issues.

**Comment by nintha** [comment]
@erickgonzalez you can compile the native library in Docker Alpine Linux Container, see it https://github.com/nintha/webp-imageio-core#compiling-the-native-library

**Comment by DavidPerezIngeniero** [comment]
But the source code isn't available any more :-(
