### ISSUE TITLE
UnsatisfiedLinkError about WebPDecoderOptions.createDecoderOptions

### ISSUE THREAD

**Issue by linicam** [nintha/webp-imageio-core#8]
Hello there I'm using your library on Mulesoft [here](https://repository.mulesoft.org/nexus/content/repositories/public/com/github/nintha/webp-imageio-core/0.1.1)

And when running the code it gives me this error:
`Exception in thread "main" java.lang.UnsatisfiedLinkError: com.luciad.imageio.webp.WebPDecoderOptions.createDecoderOptions()J
	at com.luciad.imageio.webp.WebPDecoderOptions.createDecoderOptions(Native Method)
	at com.luciad.imageio.webp.WebPDecoderOptions.<init>(WebPDecoderOptions.java:26)
	at com.luciad.imageio.webp.WebPReadParam.<init>(WebPReadParam.java:24)`

I guess it's because the .dll/.so/.dylib is not suitable for my system, which is 
> macOS High Sierra version 10.13.6

**Comment by davidekholm** [comment]
Got the same error here (OS X Mojave)

**Comment by nintha** [comment]
Sorry, I don't have any OS X device to check the `.dylib` file now. You can compile it by yourself.
[The Compilation Guide](https://github.com/nintha/webp-imageio-core#compiling-the-native-library)

**Comment by prankstrisse** [comment]
just built it for osx 64 bit, please check out a pull request https://github.com/nintha/webp-imageio-core/pull/9

**Comment by nintha** [comment]
@prankstrisse Thanks for your help. I hava merged it.
@linicam  you can try the new `.dylib` file with building jar by yourself

**Comment by davidekholm** [comment]
Thanks. Works great now!

**Comment by zonghongxia** [comment]
> 谢谢。现在很棒！

请问是怎么解决的

**Comment by d0nezer0** [comment]
how to fix this issue?  The newest version 0.1.3 still has the problem.
        <dependency>
            <groupId>com.github.nintha</groupId>
            <artifactId>webp-imageio-core</artifactId>
            <version>0.1.3</version>
        </dependency>
